# Generated by Django 3.2.5 on 2022-08-13 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_first_name', models.CharField(help_text="Author's first name", max_length=50)),
                ('author_last_name', models.CharField(help_text="Author's Last name", max_length=50)),
                ('author_email', models.EmailField(help_text='Author email id', max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(help_text=' Enter Blog title. ', max_length=100, verbose_name='Blog Title')),
                ('blog_content', models.TextField(help_text=' Write your blog here! ', max_length=2000, verbose_name='Blog Content')),
                ('blog_published', models.BooleanField(default=False)),
                ('blog_create_date', models.DateTimeField(auto_now_add=True)),
                ('blog_update_date', models.DateTimeField(auto_now=True)),
                ('blog_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.author')),
            ],
        ),
    ]
