# Generated by Django 3.2.5 on 2022-08-15 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=50)),
                ('book_isbn', models.CharField(max_length=20, unique=True)),
                ('book_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.author')),
            ],
        ),
    ]
