# Generated by Django 3.2.5 on 2022-08-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_biodata',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
