# Generated by Django 3.2.5 on 2022-08-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_author_author_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
