# Generated by Django 3.2.5 on 2022-09-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_blog_blog_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_likes',
            field=models.IntegerField(default=10),
        ),
    ]
